RaktaSewa/Controllers/BloodController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RaktaSewa.Models;
using RaktaSewa.Data;
using RaktaSewa.Services;
using RaktaSewa.Models.ViewModels;
using System.Diagnostics;


namespace RaktaSewa.Controllers
{
    public class BloodController : Controller
    {
        private readonly IBloodService bloodService;
        private readonly ILogger<BloodController> _logger;
        public BloodController(
        ILogger<BloodController> logger,
        IBloodService bloodService
        )
        {
            _logger = logger;
            this.bloodService = bloodService;
        }

        // GET: BloodController
        public IActionResult Index()
        {
            return View(new List<Blood>());
           
        }

        // GET: BloodController/Details/5
        public IActionResult Details(int Id)
        {
            return View();
        }

        // GET: BloodController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BloodController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateBlood(BloodCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var res = bloodService.Create(model);
                if (res.Item1)
                    return RedirectToAction("Index");
            }
            return View();
        }

        // GET: BloodController/Edit/5
        public IActionResult Edit(int Id)
        {
            return View();
        }

        // POST: BloodController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: BloodController/Delete/5
        //public IActionResult Delete(int Id)
        //{
        //    return View();
        //}

        // POST: BloodController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int Id)
        {
            var res = bloodService.Delete(Id);
            if (res.Item1) return RedirectToAction("Index");

            return View("Error");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RaktaSewa/Controllers/CitizenController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RaktaSewa.Models;
using RaktaSewa.Data;
using RaktaSewa.Services;
using RaktaSewa.Models.ViewModels;
using System.Diagnostics;


namespace RaktaSewa.Controllers
{
    public class CitizenController : Controller
    {
        private readonly ICitizenService citizenService;
        private readonly ILogger<CitizenController> _logger;
        public CitizenController(
        ILogger<CitizenController> logger,
        ICitizenService citizenService
        )
        {
            _logger = logger;
            this.citizenService = citizenService;
        }

        // GET: CitizenController
        public IActionResult Index()
        {
            return View(new List<Citizen>());
           
        }

        // GET: CitizenController/Details/5
        public IActionResult Details(int citizen_id)
        {
            return View();
        }

        // GET: CitizenController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CitizenController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CitizenCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var res = citizenService.Create(model);
                if (res.Item1)
                    return RedirectToAction("Index");
            }
            return View();
        }

        // GET: CitizenController/Edit/5
        public IActionResult Edit(int citizen_id)
        {
            return View();
        }

        // POST: CitizenController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: CitizenController/Delete/5
        //public IActionResult Delete(int citizen_id)
        //{
        //    return View();
        //}

        // POST: CitizenController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int citizen_id)
        {
            var res = citizenService.Delete(citizen_id);
            if (res.Item1) return RedirectToAction("Index");

            return View("Error");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RaktaSewa/Views/Blood/Create.cshtml
@model RaktaSewa.Models.Blood
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Blood</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
     
            <div class="form-group">
                <label asp-for="blood_group" class="control-label">Blood Group</label>
                <select asp-for="blood_group" class="form-control" >
                <option value="">Please select Your Blood Group</option>
                <option value="A+">A+ve</option>
                <option value="A-">A-ve</option>
                <option value="B+">B+ve</option>
                <option value="B-">B-ve</option>
                <option value="AB+">AB+ve</option>
                <option value="AB-">AB-ve</option>
                <option value="O+">O+ve</option>
                <option value="O-">O-ve</option>
               </select>
                <span asp-validation-for="blood_group" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

RaktaSewa/Views/Blood/Index.cshtml
@*using RaktaSewa.Models.ViewModels.CitizenViewModel*@
@*@model RaktaSewa.Models.ViewModels.CitizenViewModel*@
@model IEnumerable<RaktaSewa.Models.Blood>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@*<form asp-controller="Citizen" asp-action="Index" method="get">
    <p>
        <select asp-for="MovieGenre" asp-items="Model.Genres">
            <option value="">All</option>
        </select>

        Title: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>*@
<table class="table">
    <thead>
        <tr>
           <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
        
            <th>
                @Html.DisplayNameFor(model => model.blood_group)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
        
            <td>
                @Html.DisplayFor(modelItem => item.blood_group)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>